# Copyright 2022-2023 LunarG, Inc.
#
# SPDX-License-Identifier: Apache-2.0

name: Linux

on:
    push:
    pull_request:
        branches:
            - main

env:
  CMAKE_GENERATOR: Ninja
            
permissions:
    contents: read

jobs:
  ubuntu-cmake-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.17.0
      - name: Configure Vulkan-Headers
        run: cmake -S . -B build
      - name: Install Vulkan-Headers
        run: cmake --install build --prefix ${{ github.workspace }}/build/install
      - name: Test Vulkan-Headers find_package support
        run: cmake -S tests/find_package -B build/tests/find_package -D CMAKE_PREFIX_PATH=${{ github.workspace }}/build/install

  ubuntu-cmake-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.25.0
      - name: Configure Vulkan-Headers
        run: cmake -S . -B build -D BUILD_TESTS=ON --log-level=DEBUG
      - name: Build Vulkan-Headers Tests
        run: cmake --build build

  test-cmake-minimum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.15.0
      - name: Configure Vulkan-Headers
        run: cmake -S . -B build/ --loglevel=DEBUG
      - name: Install Vulkan-Headers
        run: cmake --install build/ --prefix build/install

  ubuntu-cmake-add_subdirectory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - name: Test add_subdirectory support
        run: cmake -S tests/add_subdirectory -B tests/add_subdirectory/build
      - name: Build
        run: cmake --build tests/add_subdirectory/build

  reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
